POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Annisa test",
    "email": "anns@devscale.id",
    "password": "bisabisa"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "anns@devscale.id",
    "password": "bisabisa"
}

